name: 01 -  Confguration 2 of 2

on:
  workflow_dispatch:
    inputs:
      runtime_privileged:
        type: boolean
        default: false
      runtime_virtual_host:
        default: 'pknw1.co.uk'
      runtime_virtual_port:
        default: '80'
      runtime_restart_policy:
        default: 'unless_stopped'
      puid_guid:
        default: '666:666'

jobs:
  display_inputs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ORG_TOKEN }}
      - name: summarise inputs
        run: |
          echo "## Base Input Values" >> $GITHUB_STEP_SUMMARY
          echo "runtime_privileged: ${{ inputs.runtime_privileged }}" >> $GITHUB_STEP_SUMMARY
          echo "runtime_virtual_host: ${{ inputs.runtime_virtual_host }}" >> $GITHUB_STEP_SUMMARY
          echo "runtime_virtual_port: ${{ inputs.runtime_virtual_port }}" >> $GITHUB_STEP_SUMMARY
          echo "runtime_restart_policy: ${{ inputs.runtime_restart_policy }}" >> $GITHUB_STEP_SUMMARY
          echo "puid_guid: ${{ inputs.puid_guid }}" >> $GITHUB_STEP_SUMMARY


  store_inputs:
    runs-on: ubuntu-latest
    needs: display_inputs
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ORG_TOKEN }}
      - uses: action-pack/set-variable@v1
        with:
          name: 'runtime_privileged'
          value: '${{ inputs.runtime_privileged }}'
          token: ${{ secrets.GH_ORG_TOKEN }}
        with:
          name: 'runtime_virtual_host'
          value: '${{ inputs.runtime_virtual_host }}'
          token: ${{ secrets.GH_ORG_TOKEN }}
        with:
          name: 'runtime_virtual_port'
          value: '${{ inputs.runtime_virtual_port }}'
          token: ${{ secrets.GH_ORG_TOKEN }}
        with:
          name: 'runtime_restart_policy'
          value: '${{ inputs.runtime_restart_policy }}'
          token: ${{ secrets.GH_ORG_TOKEN }}
        with:
          name: 'puid_guid'
          value: '${{ inputs.puid_guid }}'
          token: ${{ secrets.GH_ORG_TOKEN }}


  display_variables:
    runs-on: ubuntu-latest
    needs: store_inputs
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ORG_TOKEN }}
      - name: summarise inputs
        run: |
          echo "## Base Config Variables" >> $GITHUB_STEP_SUMMARY
          echo "runtime_privileged : ${{ vars.runtime_privileged }}" >> $GITHUB_STEP_SUMMARY
          echo "runtime_virtual_host : ${{ vars.runtime_virtual_host }}" >> $GITHUB_STEP_SUMMARY
          echo "runtime_virtual_port : ${{ vars.runtime_virtual_port }}" >> $GITHUB_STEP_SUMMARY
          echo "runtime_restart_policy : ${{ vars.runtime_restart_policy }}" >> $GITHUB_STEP_SUMMARY
          echo " puid_guid : ${{ vars.puid_guid }}" >> $GITHUB_STEP_SUMMARY


